### ISSUE TITLE
When turning turbo mode on/off, the menu will not automatically close

### ISSUE THREAD

**Issue by swlibi** [mozilla-tw/FirefoxLite#5283] opened 2020-07-22 09:39 UTC
**Describe the bug**
When turning turbo mode on/off, the menu will not automatically close

**Steps To Reproduce**
1. Go to visit a website
2. Tap [Menu]
3. Tap [Turbo mode]
4. The menu will not automatically close

**Expected behavior**
The menu will automatically close

**Actual behavior**
The menu will not automatically close

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Device info (please complete the following information):**
 - Device: ASUS ZenFone Max
 - OS: Android 9
 - Webview 84.0.4147.89
 - Version 2.5.0 (20416) Beta

**Reproduce rate**
5/5

**Additional context**

**Comment by youwenliang** [comment] 2020-07-22 09:42
I think this is expected, tag @tinahsieh to confirm.

**Comment by tinahsieh** [comment] 2020-07-22 14:18
Hey George,
It's not a bug. I asked the devs to not dismissing the menu after toggling so that users can see the toggle status. 
I'll close this ticket. Feel free to ping me if the behavior is odd for you!

**Closed by tinahsieh** 2020-07-22 14:18 UTC
Labels: need triage
