### ISSUE TITLE
Crash when opt out 'Send usage data' in settings

### ISSUE THREAD

**Issue by jarceit** [mozilla-tw/FirefoxLite#3498] opened 2019-04-21 20:29 UTC
**Describe the bug**
A browser crashes after a while when I opt out 'send usage data' in settings.

**Steps To Reproduce**
1. Go to 'settings'.
2. Opt out 'send usage data'.
3. Use Firefox lite without any errors for a while.
4. See crash.
5. Subsequent crashes follow the first crash.

**Expected behavior**
Not to crash

**Actual behavior**
Crash: I can't open the browser, it just crashes. I can launch it without crashes after wiping all the data.

**Device info (please complete the following information):**
 - Device: Redmi 4x
 - OS: LineageOS 15.1
 - Webview: 72.0.3626.121
 - Version: 1.3.1(11115)

**Reproduce rate**
10 / 10

**Additional context**

**Comment by mTwTm** [comment] 2019-04-22 02:44
@Daisy-pliu This looks like a high priority task, can you take a look?

**Comment by Daisy-pliu** [comment] 2019-04-22 04:07
can not reproduce with our Redmi device .

**Test step :**[steps](https://github.com/mozilla-tw/FirefoxLite/issues/3498#issue-435545052)
**device:** 
-  Device: redmi 4x
-  OS : android 7.1.2
- webview:  73.0.3683.90
- version: 1.3.1(11115) dev build 

Probably issue related to Lineage OS 15.1, OS specific issue.

**Comment by mTwTm** [comment] 2019-04-22 05:39
@jarceit it will be helpful if you can provide the crash log.

**Comment by jarceit** [comment] 2019-04-22 10:18
Thanks for the answer, here's the logcat: 

[logcat.txt](https://github.com/mozilla-tw/FirefoxLite/files/3103008/logcat.txt)

**Comment by mTwTm** [comment] 2019-04-22 22:10
Seems like the Firebase is not initialized when not possible but we still try to stop it when the toggle is switched. @Daisy-pliu we might want to test if this happens on all devices that doesn't have play-services.

**Comment by Daisy-pliu** [comment] 2019-04-23 02:46
can not reproduce on Pixel 2 (android 9.0), Samsung (8.0)  
Precondition: disable play store app & install APK directly
Test step: [steps](https://github.com/mozilla-tw/FirefoxLite/issues/3498#issue-435545052)
version : 1.3.1 (11115) RC build

We probably can reproduce it on LineageOS 15.1 but I am not sure if it a right decision to go deeper which might be the product concern.

**Comment by chianger** [comment] 2019-05-28 09:14
no action from the dev team. won't fix

**Closed by chianger** 2019-05-28 09:14 UTC
