### ISSUE TITLE
Getting in and out the app with Download Panel open will have strange behavior

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/FirefoxLite#3111] opened 2019-01-24 10:10 UTC
**Describe the bug**
Getting in and out the app with Download Panel open will have strange behavior

**Steps To Reproduce**
1. Open Download Panel
2. Press "Home" button and leave the app
3. Enters the app again from recent app

**Expected behavior**
The entries are not duplicated /progress should update normally

**Actual behavior**
with developer option "Don't Keep activity": Entry duplicated
without developer option "Don't Keep activity": Progress Not update 

**Reproduce rate**
100%

**Comment by Daisy-pliu** [comment] 2019-01-29 09:40
Confirm with @josephyu1110 about reproduction steps

**Describe the bug**
Getting in and out the app open download panel when downloading files will have strange behavior

**SC1**
**Precondition:**
1. File is downloading 
2. open developer option "Don't Keep activity":
**Steps To Reproduce**
    1. Open Download Panel
    2. Press "Home" button and leave the app
    3. Enters the app again from recent app

**Expected behavior**
The entries are not duplicated /progress should update normally

**Actual behavior**
 Download item is duplicated and download progress is not updated


**SC2**
**Precondition:**
1. File is downloading 
2. don't turn on developer option "Don't Keep activity":
**Steps To Reproduce**
    1. Open Download Panel
    2. Press "Home" button and leave the app
    3. Enters the app again from recent app

**Expected behavior**
The entries are not duplicated /progress should update normally

**Actual behavior**
downloaded item is not duplicated but download progress is not updated

**Reproduce rate**
100%

**Comment by Daisy-pliu** [comment] 2019-02-15 06:26
Verification : ❌
Device :Samsung s7 edge (8.0)
SC1: FAIL -> it shows duplicated entry
SC2:  FAIL  -> it shows duplicated entry
SC3 : PASS

Device :Redmi 4x (7.1.2)
SC1: FAIL -> it shows duplicated entry
SC2:  FAIL -> it shows duplicated entry
SC3 : PASS

Device :Google Pixel 2 (9.0)
SC1: FAIL  -> it shows duplicated entry
SC2:  FAIL -> it shows duplicated entry
SC3 : FAIL -> after back from recent app the download status is paused

**Comment by josephyu1110** [comment] 2019-02-18 07:01
SC1 & SC2 will get to be fixed once this [PR](https://github.com/mozilla-tw/FirefoxLite/pull/3122) is merged.
For Device :Google Pixel 2 (9.0)
SC3 : FAIL -> after back from recent app the download status is paused
@Daisy-pliu Could you help to provide the video? Reproducible rate? Thanks!

**Comment by Daisy-pliu** [comment] 2019-02-18 07:15
updated video link on [comment](https://github.com/mozilla-tw/FirefoxLite/issues/3111#issuecomment-463923546)
reproduce rate : 10/10

**Comment by josephyu1110** [comment] 2019-02-20 03:57
From the video, the download turns to "Paused" state when app enters into background mode.
<img width="321" alt="screen shot 2019-02-20 at 11 34 04 am" src="https://user-images.githubusercontent.com/16300853/53065093-357cf100-3505-11e9-93ef-25e3e7927ddf.png">
The DUT's battery saver mode is on as below figure shown. Since [Android 9](https://developer.android.com/about/versions/pie/power#battery-saver) will restrict app's network access once the battery saver mode is on and app is in background. Confirmed with @Daisy-pliu , download progress can be resumed once the battery saver mode is turned off.
<img width="333" alt="screen shot 2019-02-19 at 3 17 15 pm" src="https://user-images.githubusercontent.com/16300853/53065095-3c0b6880-3505-11e9-8ec3-081854664d9e.png">

**Comment by chianger** [comment] 2019-02-27 07:11
since #3122 was merged, close this and let @Daisy-pliu to verify.

**Closed by chianger** 2019-02-27 07:11 UTC
Labels: QAwanted

**Comment by Daisy-pliu** [comment] 2019-03-04 03:28
Verification : ✅
Test version :  1.1.4 (10373)
Webview: 72.0.3626.105
**Device :Google Pixel 9.0 （without battery saving turn on）**
SC1: PASS
SC2:  PASS
SC3 : PASS
**Device :Redmi 4X (7.1.2) **
SC1: PASS
SC2:  PASS
SC3 : PASS

**Device : OPPO(7.1.1)**
SC1: PASS
SC2:  PASS
SC3 : PASS
