### ISSUE TITLE
strictmode.DiskReadViolation - PinSiteManager.kt:67)

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/FirefoxLite#3483] opened 2019-04-18 02:58 UTC
StrictMode policy violation; ~duration=21 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
        at java.io.File.exists(File.java:815)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:605)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:596)
        at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:552)
        at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:747)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:400)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:174)
        at org.mozilla.rocket.home.pinsite.SharedPreferencePinSiteDelegate.<init>(PinSiteManager.kt:67)
        at org.mozilla.rocket.home.pinsite.PinSiteManagerKt.getPinSiteManager(PinSiteManager.kt:27)
        at org.mozilla.focus.home.HomeFragment.onActivityCreated(HomeFragment.java:629)
        at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2460)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1483)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:814)
        at org.mozilla.focus.navigation.TransactionHelper.showHomeScreen(TransactionHelper.java:56)
        at org.mozilla.focus.navigation.ScreenNavigator.popToHomeScreen(ScreenNavigator.java:157)
        at org.mozilla.focus.activity.MainActivity.firstrunFinished(MainActivity.java:967)
        at org.mozilla.focus.fragment.FirstrunFragment.finishFirstrun(FirstrunFragment.kt:179)
        at org.mozilla.focus.fragment.FirstrunFragment.onClick(FirstrunFragment.kt:130)
        at org.mozilla.focus.fragment.FirstrunFragment$wrapButtonClickListener$1.onClick(FirstrunFragment.kt:171)

**Comment by pharspher** [comment] 2019-04-18 03:24
duplicate of #3459

**Closed by pharspher** 2019-04-18 03:24 UTC
