### ISSUE TITLE
on-boarding shouldn't block pendingUrl

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/FirefoxLite#3454] opened 2019-04-12 07:43 UTC
this is a follow up for https://github.com/mozilla-tw/FirefoxLite/pull/3453#issue-269902695

Previously, pendingUrl is used for:
1. In `onCreate()` cache the Url from the coming intent and display on-boarding if needed
2. In `onNewIntent()`, cache the Url from the coming intent and display on-boarding if needed
3. In `onNewIntent()`, cache the Url from the coming intent load the Url after fragments are resumed.
#3452 removed scenario 2.
Now, this PR removed scenario 1.
Now pendingUrl is only used for scenario 3.

Since Firstrun could come late and the user had already started to use the app. We should load the Url directly when the intent comes and don't wait for on-boarding is shown.

ps @Jacklin-ux has confirmed this behaviour change.

**Comment by Daisy-pliu** [comment] 2019-05-07 05:45
@Jacklin-ux  could you double check the test steps? 

**Test Case**
1. vpn in indonesia
2. launch app 1.5.1
3. swipe up to see life feed
4. kill app
5. launch and see [discover new things] on boarding
6. open gamail app
7. long click on any text
8. tap [web search] -> [firefox lite]

**Expect Result:**
should see requested text search page on Lite successfully

**Comment by benjamin-cheng** [comment] 2019-05-07 08:42
@cnevinc would you like to merge PR #3455 to close this issue?

**Comment by Daisy-pliu** [comment] 2019-05-07 08:55
@Jacklin-ux  found app hanging at step 8 when perform [test case ](https://github.com/mozilla-tw/FirefoxLite/issues/3454#issuecomment-489917137) on Piexl3, Android 9, Chrome (74.0.3729.136), Lite 1.5.1 (11850). 

However I can not reproduce his issue on my test device for Samsung 8.0, Pixel 2 (9.0), on Version 1.5.1 (11850) nightly, webview: 74.0.3729.92.

**Comment by cnevinc** [comment] 2019-05-07 20:28
> However, if user do more steps as below
> 9. tap [recent app]
> 10. tap [firefox lite nightly] app -> a

Did you test the local build? Cause I think #3455 is not merged yet.

**Comment by Daisy-pliu** [comment] 2019-05-08 00:48
Since some code were landed I was doing a pretesting to have some insight and confirm test steps. Additionally some was saying it is finished and merged long time ago which is probably a miscommunication. 
In general the testing will be conducted by the time the ticket is closed.

**Closed** 2019-05-08 02:20 UTC

**Comment by Daisy-pliu** [comment] 2019-05-10 06:05
verify : ✅
This ticket is in the purpose of testing such [test scenario](https://github.com/mozilla-tw/FirefoxLite/issues/3454#issuecomment-489917137). However after [life feed enhancement](https://github.com/mozilla-tw/FirefoxLite/issues/3402) is landing, we wont have this test scenario. 
This ticket can see it as  enhancement if we have remote config with on boarding page feature in the near future.

**Comment by Daisy-pliu** [comment] 2019-05-15 03:26
Verify : ✅
Version: nightly 1.6.0 (12105) 
Device: vivo 6.0.1

Test case:
1. fresh install app
2. not skip onboarding
3. open Gmail
4. long click any text 
5. tap [web search]
6. tap [firefox lite]

result:
search selected text with firefox lite successfully.
