### ISSUE TITLE
[Telemetry] error in url_counts 

### ISSUE THREAD

**Issue by lanyliu** [mozilla-tw/FirefoxLite#4824] opened 2020-03-18 05:56 UTC
**Describe the bug**

event method: end  
event object: tab_swipe
event extra: url_counts

error:
url_counts should = 0

**Steps To Reproduce**
1. Go to 'shopping search'
2. see Google tab
3. switch to second tab
4. will receive url_counts=0

**Expected behavior**
url_counts should >= 1

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/49740335/76929866-2b077380-6920-11ea-9acb-402429f9725c.png)

**Comment by chianger** [comment] 2020-03-20 02:49
Looks like we're gonna block this for 2.1.12

**Comment by shsu571** [comment] 2020-03-20 03:48
Mark already confirmed yesterday. This is not block, but should be fixed on next sprint.

**Closed** 2020-03-20 06:24 UTC
Labels: P0, V-SHOPPING, need BI audit, size: S

**Comment by yshlin** [comment] 2020-03-20 08:13
Verified seeing url_counts=1
