### ISSUE TITLE
Crash after repeatedly add new tab and back

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#3355] opened 2019-03-20 15:16 UTC
**Steps To Reproduce**
1. launch app with India SIM
2. skip on boarding 
3. tap [settings] -> [newspoint ]
4. tap back key
5. swipe up
6. tap any [news]
7. tap [add new tab]
8. tap system back
9. repeat  step 7~8  for 5 times

**Expected behavior**
see home page

**Actual behavior**
crash and show [Firefox lite is stopped] 

**Screenshots/videos**
[video](https://drive.google.com/file/d/1i2Tfs1l4_8Ue44dgqMbzclIkd3cH3Jjv/view?usp=sharing)

**Device info (please complete the following information):**
 - Samsung 8.0

**Reproduce rate**
10/10

**Note**
it not happened on "DainikNhaskar.com", only happened on "Newspoint"

**Comment by cnevinc** [comment] 2019-03-20 16:38
I can't reproduce using below steps using Dev build:
https://drive.google.com/file/d/1UCNziOhbJXH-twvM-rdkQ-FHOF56C9_B/view?usp=sharing

I also can't find the crash cymbal in Android Vitals and Crashlytics so it makes debugging a little bit harder.

I'll use the phone wih India sim card to test again tomorrow.

**Comment by chianger** [comment] 2019-03-21 02:47
I tried many times and cannot reproduce. Daisy who originally posted this can no longer reproduce either. This shall not block beta.

**Comment by chianger** [comment] 2019-03-21 03:04
tagging QAWanted to continue monitoring this

**Comment by chianger** [comment] 2019-03-29 02:06
let's test on a few more devices again. if not reproducible let's close it as WORKSFORME

**Comment by Daisy-pliu** [comment] 2019-03-29 02:08
Not see this issue happened again from 2019.3.25 ~2019.3.29 from Samsung 8.0, Redmin 7.0, Oppo 6.1. As #3289 will reduce the impact of this issue, I suggest we close this one.

**Closed** 2019-03-29 02:57 UTC
Labels: QAwanted, S1

**Comment by Daisy-pliu** [comment] 2019-03-29 10:27
verify: ✅
Test version :1.3.0 (11070)
Test device :Samsung 8.0
Test pre-condiction: remote life_feed feature and url is on and mobile with India SIM
Test step: [steps](https://github.com/mozilla-tw/FirefoxLite/issues/3355#issue-423309926)
