### ISSUE TITLE
[Smoke Test] Screenshot animation doesn't start right after appearing

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/FirefoxLite#673] opened 2017-09-08 02:20 UTC
As title. Not 100% reproducible.

Build: 855
DuT: Samsung, Advan, Andromax

**Comment by mTwTm** [comment] 2017-09-08 02:31
Expected since a part is done on main thread and thus there is a brief while we can't do updates depending on device capability. I'll assign this to Max since he is looking into this.

**Comment by Conjuror** [comment] 2017-09-12 07:46
related to #559

**Comment by chianger** [comment] 2017-09-12 07:47
leave it open but #559 likely will fix this as well.

**Comment by Conjuror** [comment] 2017-10-06 03:05
The issue is still there and we will see the animation flashes a little bit in the beginning.

**Comment by NashTung** [comment] 2018-05-11 07:13
Work for me.
Video:
https://drive.google.com/open?id=1s74jokX01jcN-W5acf7u2YcLYmUqIdyZ

Device: Advan i5C
Rocket: 2.0.0(4168).nightly
Android: 5.1
Android Webview: 51.0.2704.81

**Closed** 2019-04-16 02:12 UTC
Labels: Comp/ScreenCapture, S3, Verified
