### ISSUE TITLE
Allow screen rotation

### ISSUE THREAD

**Issue by mossroy** [mozilla-tw/FirefoxLite#3258] opened 2019-03-06 11:43 UTC
**User story**
As a user of Firefox Lite, I would like the screen content to rotate when I rotate the device

**Acceptance Criteria (how do I know when I’m done?)** 
1. Go to any website (in portrait mode)
2. Rotate the device, to put it in landscape mode
3. Check that the website content as rotated, so that you can see it in landscape mode

**Comment by mTwTm** [comment] 2019-03-06 11:46
Duplicate of #1231

**Closed by mTwTm** 2019-03-06 11:46 UTC
