### ISSUE TITLE
Tap a link on a website, the new tab is not focused

### ISSUE THREAD

**Issue by witsmo** [mozilla-tw/FirefoxLite#3065] opened 2019-01-14 02:04 UTC
**Describe the bug**
Tap a link on a website, the new tab is not focused

**Steps To Reproduce**
1. Launch Rocket
2. Visit website https://www.hinet.net/mobile.html --> Tab#1
3. Add a new tab ex: Youtube  --> Tab #2
4. Back to the Tab#1 fr
5. Tap a link on a website
    b. News (2nd point b)
6. go to tab tray

**Expected behavior**
The new tab is focused and placed after right the previous tab #1 

**Actual behavior**
The new tab is not focused, wait for a minute, the app forced stop

**Screenshots/videos**
Video:
https://drive.google.com/file/d/1rKfPATuN-glgRY9XZJENhl-NjYWOZ6da/view?usp=sharing
ADB issue Log:
https://drive.google.com/file/d/1blOhimJfV-YF3RbqjKrV9otQajHfb0va/view?usp=sharing

**Device info (please complete the following information):**
 - Device: Nexus 6, LG Phonix 2
 - OS: Android 6.0.1, Android 6.0
 - Webview: 
          72.0.3626.53 for Nexus 6
          72.0.3626.14 for LG Phonix 2
 - Version: 1.0.9(9310).nightly

**Reproduce rate**
5/5

**Additional context**
N/A

### put correct labels ###
S2

**Comment by Daisy-pliu** [comment] 2019-01-14 02:40
Can reproduce on certain device: 
1. Nexus 5 (6.0.1) , webview 72.0.4626.28

**Comment by witsmo** [comment] 2019-01-14 03:10
I update the webview version on Device info, thanks.
72.0.3626.53 for Nexus 6
72.0.3626.14 for LG Phonix 2

**Comment by Daisy-pliu** [comment] 2019-01-14 03:51
Can reproduce on :

**Comment by chianger** [comment] 2019-01-22 08:00
This seems to be only affected with webview 72 according to previous report.

**Comment by chianger** [comment] 2019-01-25 09:09
QAWanted to verify again on latest 72, and also try if there's other website to reproduce.

**Comment by Daisy-pliu** [comment] 2019-01-28 06:54
Verification : ❌
Test build : 1.0.10 (9617), webview 72.0.3626.73 (latest beta)
Test device: Redmi 5 plus (7.1)

**Comment by joechengla** [comment] 2019-02-11 08:59
seems to be fixed on 72.0.3626.96

**Comment by Daisy-pliu** [comment] 2019-02-11 09:14
If user update chrome the webview upgrade to 72.0.3626.96 then this issue will not happen.
Verify : ✅
Device: Samsung s7 edge (8.0)
Webview: 72.0.3626.96
Build:1.0.10 (9617)
Scenario: 
1. [Hinet news open tab](https://github.com/mozilla-tw/FirefoxLite/issues/3065#issue-398727078) 
2. [Ads in IndiaTimes](https://github.com/mozilla-tw/FirefoxLite/issues/3065#issuecomment-458017002),
3.[Twitter link in BBC news](https://github.com/mozilla-tw/FirefoxLite/issues/3065#issuecomment-458017002)

**Comment by chianger** [comment] 2019-02-12 03:37
not happening with my testing with webview 72.0.3626.96

**Closed by chianger** 2019-02-12 03:37 UTC
Labels: Crash, QAwanted, S1, Verified
