### ISSUE TITLE
When downloading files, sometimes the file's format is changed to ".bin"

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#5296] opened 2020-07-29 03:32 UTC
**Describe the bug**
Sometimes some file types that are downloaded change the format of the extension (like from .mkv to .bin.). There is no access to change the storage area.

**Reproduce rate**
How many times you can reproduce such issue, given the testing rounds
Not sure

**Additional context**

**Comment by cnevinc** [comment] 2020-07-29 10:21
We'll need a reproduce step.

**Comment by cnevinc** [comment] 2020-07-30 06:18
Tested on my device. 
Reproduce Step:
- Go to https://msrp-dev01.appspot.com/api/v1/admin/push/ui?token=3
- Click "download"
- Go to Download Panel
- The file name is download.bin

cause:
Android DownloadManager automatically adds `bin` as the extension to the file without a file extension.

action item
- I don't think there's anything we can do. Since we don't know the mime type of that file.
- close this bug

**Comment by youwenliang** [comment] 2020-07-30 06:23
@cnevinc is it possible that we just don't add the .bin even if there's no extension to the files?

**Comment by youwenliang** [comment] 2020-07-30 08:01
I also encounter another issue, when the download started, it will show Unknown (Pending...) on the Download Panel, look like broken to me, but still download successfully after a while.

![image](https://user-images.githubusercontent.com/8919308/88897470-e69cc480-d27d-11ea-82dc-5c5553d66b73.png)

**Comment by cnevinc** [comment] 2020-07-30 08:21
> I also encounter another issue, when the download started, it will show Unknown (Pending...) on the Download Panel, look like broken to me, but still download successfully after a while.
> 

Please create another issue for this new issue

**Comment by cnevinc** [comment] 2020-07-30 08:33
> dd the .bin even if there's no extension to the file

this is doable. Just not sure what's the impact and what issue we want to solve here.

**Comment by youwenliang** [comment] 2020-07-30 09:06
Just to resolve confusion from the users and divert the source of problem to the file servers, not to the browser.

Feedback from the users related to the "bin" issue:
![image](https://user-images.githubusercontent.com/8919308/88903882-ed7c0500-d286-11ea-92e7-51427d17bdb9.png)

**Comment by cnevinc** [comment] 2020-07-31 09:04
on it

**Closed** 2020-08-04 07:19 UTC
Labels: P0, size: S
